### ISSUE TITLE
add ability to consume alert messages in dl3

### ISSUE THREAD

**Issue by laroque** [driplineorg/dripline-cpp#13]
On first pass we will only allow this in the service (not in a child endpoint, because it could be subtle to decide which child(ren) should process a given message). In sort_message we should evaluate the message objects type in an outer conditional block, requests to be handled as they are, alerts per this approach.

**Comment by nsoblath** [comment]
The service class should have a set of keys (user-supplied) that it binds to the alerts exchange.

**Comment by laroque** [comment]
`bind_keys` is now virtual, as is `on_alert_message`, details of consuming are implemented in dripline-python
