### ISSUE TITLE
consider defined returncodes

### ISSUE THREAD

**Issue by laroque** [driplineorg/dripline-cpp#29]
The standard per https://github.com/driplineorg/dripline/blob/develop_dl3/Wire-Protocol.rst#return-codes has "Application Error" vs "Device Error" in the CPP

While we're thinking about it, I think we may want to add two (which 

- `NotImplementedError` -> you tried to execute a function which is implemented but expects to be overridden before use (pure virtual was overridden just to throw this error)
- `ApplicationConfigurationError` -> the application/service has reached a point where the thing you're requesting is not compatible with the current configuration, but it may be a thing that this service could do under a different configuration.

**Comment by nsoblath** [comment]
See driplineorg/dripline#15

**Comment by nsoblath** [comment]
Preempted by #41
