### ISSUE TITLE
Maybe a typo?

### ISSUE THREAD

**Issue by yadiw** [driplineorg/dripline-cpp#35]
https://github.com/driplineorg/dripline-cpp/blob/2110f3e742e05e1540e2e265fe80a991bda392be/library/message.hh#L366

https://github.com/driplineorg/dripline-cpp/blob/2110f3e742e05e1540e2e265fe80a991bda392be/library/message.hh#L373

**Comment by nsoblath** [comment]
Definitely a typo

**Comment by nsoblath** [comment]
Fixed in 4e67517fdad091c625271550d6150461ee25290b
