### ISSUE TITLE
helper for decoding return codes to string representations

### ISSUE THREAD

**Issue by laroque** [driplineorg/dripline-cpp#5]
At low priority (we can just go look at the spec), it would be nice to be able to convert return codes to the [string descriptions](https://github.com/driplineorg/dripline/blob/master/Wire-Protocol.rst#return-codes) from the dripline spec.

It would be great if there was a meta programming solution and/or if it could be included as part of the existing macros.

Priority is quite low.

**Comment by nsoblath** [comment]
Completed in 8dfa717
