### ISSUE TITLE
the dl-agent tool returns a segmentation violation instead of message return code.

### ISSUE THREAD

**Issue by laroque** [driplineorg/dripline-cpp#55]
as described in [dripline-python 88](github.com/driplineorg/dripline-cpp/issues/#88), the `dl-agent` tool seems to be exiting with 137, rather than expected return codes.

**Comment by nsoblath** [comment]
This turned out to be related to a container exiting before `dl-agent` had finished execution.  See driplineorg/dripline-python#88.
