### ISSUE TITLE
request different dl_agent's output behavior

### ISSUE THREAD

**Issue by laroque** [driplineorg/dripline-cpp#8]
There are a couple of concerns/requests here that probably warrant discussion:

1. While psyllid is an application that takes some flags, dl_agent is a command-line tool, and so the expected output behavior is different. In particular:
   - a RELEASE build should probably not print `PROG` statements (application lines 102 and 103)
   - the "output" of the command should go to STDOUT (so it can be piped to other tools like grep), and ideally all logging messages would go to STDERR

2. It would be very useful to be able to retrieve the Reply_Message's return code, perhaps a flag to have dl_agent return with the code of its Reply, possibly returning that instead of the message body, maybe someone has another idea?

3. It would be useful/intuitive if the command output were.... the reply message payload? a representation of the full reply object (including both payload and headrs)? something else? ... Ideally we'd have some flags to allow several of these cases.

**Comment by wcpettus** [comment]
context: we want to use dl_agent to query the psyllid daq-status endpoint, then we can have a liveness probe which crashes the container if status=200

in the current state this isn't possible, dl_agent doesn't return the payload, so we can't check the actual status value, which limits its functionality as a command line tool

**Comment by nsoblath** [comment]
We can address (1) by replacing the out stream in `scarab::logger` with `std::cerr` at the beginning of `dl_agent.cc`.  Then the message body itself can be output using `std::cout`.

The message body should be output as standardized JSON for maximum usefulness by users.

**Comment by nsoblath** [comment]
(2) should become the standard way to output return values.  This will benefit from the proposal in driplineorg/dripline#13.

**Comment by nsoblath** [comment]
Initially, at least, (3) can be easily accomplished by using `message::encode_message_body()`.  However, in dl2 (dl-cpp v1) this is the payload plus a few other fields, and in dl3 this will be just the payload.

**Comment by nsoblath** [comment]
So, on (2), I take back what I said earlier.  As I should have remembered, POSIX exit codes are between 0 and 255.  Therefore we can't use the dripline return code for the application exit code.

**Comment by nsoblath** [comment]
(1), (2), and (3) are done in 19783d6726a40420135d9496fa6da2c06efbe36b (feature branch, so far).
